### ISSUE TITLE
Test performance of Protobuf vs Capnproto 

### ISSUE THREAD

**Issue by l0k18** [dusk-network/bls12_381-sign#20]
**Performance of gRPC/protobuf is less than Cgo** 
Benchmarking data shows that handling the parameters is the first bottleneck and second is handling return values, in both the Go and Rust side.

**Memory allocation seems to be the big bottleneck**
 The Go side all of the memory handling is coming from the generated gRPC/Protobuf (most likely protobuf is half at least) and on Rust it is with slice/vector iterators and obviously some part must be coming from the serialization and RPC processing. Thus, with it's far lower memory handling footprint, Capnproto in place of Protobuf may yield performance that puts the microservice implementation ahead of the Cgo, and slightly simplifying Go/Rust interop.

**Previous work**
The initial Cgo over Rust FFI, and now the gRPC/Protobuf both have yielded results with an undesirable amount of overhead in processing. Eventually the blockchain node is in pure Rust and this is not a problem, but in between, this sort of thing is important.

**Additional context**
N/A

**Comment by herr-seppia** [comment]
Closing as obsolete
