### ISSUE TITLE
Add CHANGELOG.md to this repo

### ISSUE THREAD

**Issue by ZER0** [dusk-network/bls12_381-sign#30]
**Describe what you want implemented** 
This repo needs a CHANGELOG to keep track of the changes across versions and releases.

**Describe "Why" this is needed**
Without a CHANGELOG it's hard to keep trace of what happened.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by moCello** [comment]
Will be tackled together with #66
